name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - run: sbt '++ 3.1.0!' munitNative/compile
